spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/projet_sgbd_2025
    username: postgres
    password: nikesakou11
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
          hibernate:
            format_sql: true

server:
    port: 8080